// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQnYAg_69XKlcNx7bbHCEK1lD3Dg-pYiU',
    appId: '1:470481420965:web:54f5ce4b5c5f70c11d834c',
    messagingSenderId: '470481420965',
    projectId: 'linkyou-fd0c2',
    authDomain: 'linkyou-fd0c2.firebaseapp.com',
    storageBucket: 'linkyou-fd0c2.appspot.com',
    measurementId: 'G-Z5S01F89EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIuI20QC6QoNBfwk7J5V9a2CcapoQmzw',
    appId: '1:470481420965:android:d90d079bc1c4842f1d834c',
    messagingSenderId: '470481420965',
    projectId: 'linkyou-fd0c2',
    storageBucket: 'linkyou-fd0c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFTbxIStULXg64NnUE5QpgD9nT-rodps',
    appId: '1:470481420965:ios:8b6858cfc73f187b1d834c',
    messagingSenderId: '470481420965',
    projectId: 'linkyou-fd0c2',
    storageBucket: 'linkyou-fd0c2.appspot.com',
    androidClientId: '470481420965-cnee4aau05s09t8lh9mb3lj3apqct6op.apps.googleusercontent.com',
    iosClientId: '470481420965-9uov6831h1tb0t0u6et1psm7rgrhj4ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoFTbxIStULXg64NnUE5QpgD9nT-rodps',
    appId: '1:470481420965:ios:8b6858cfc73f187b1d834c',
    messagingSenderId: '470481420965',
    projectId: 'linkyou-fd0c2',
    storageBucket: 'linkyou-fd0c2.appspot.com',
    androidClientId: '470481420965-cnee4aau05s09t8lh9mb3lj3apqct6op.apps.googleusercontent.com',
    iosClientId: '470481420965-9uov6831h1tb0t0u6et1psm7rgrhj4ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkyou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQnYAg_69XKlcNx7bbHCEK1lD3Dg-pYiU',
    appId: '1:470481420965:web:d1896a99e531d7691d834c',
    messagingSenderId: '470481420965',
    projectId: 'linkyou-fd0c2',
    authDomain: 'linkyou-fd0c2.firebaseapp.com',
    storageBucket: 'linkyou-fd0c2.appspot.com',
    measurementId: 'G-C6KJ0T8NHR',
  );

}